/* ==========================================================================
   AI-ASSISTANT LOCK: DO NOT EDIT THIS FILE OR ITS LOGIC WITHOUT EXPLICIT 
   PERMISSION FROM THE USER. THIS APPLIES TO CORE/CRITICAL LOGIC.
   ========================================================================== */

import React from 'react';
import { Document, Page, View, Image } from '@react-pdf/renderer';

// Import styles
import { styles } from './PDFStyles';
import { RoomService } from '../../services/RoomService';
import PDFHeader from './layout/PDFHeader';
import PDFFooter from './layout/PDFFooter';
import PDFMetaData from './layout/PDFMetaData';
import DescriptionSection from './sections/DescriptionSection';
import RoomDocumentation from './sections/RoomDocumentation';
import PlansSection from './sections/PlansSection';
import CauseSection from './sections/CauseSection';
import MeasuresSection from './sections/MeasuresSection';
import MeasurementsSection from './sections/MeasurementsSection';
import DataLoggerSection from './sections/DataLoggerSection';



const DamageReportDocument = ({ data }) => {
    console.log("PDF Document: Rendering with staticMapUrl:", !!data.staticMapUrl);
    if (data.staticMapUrl) {
        console.log("PDF Document: staticMapUrl length:", data.staticMapUrl.length);
    }

    // Filter rooms that have content (images or existing logic)
    // The previous logic filtered logic based on filtering dataToUse.images.
    // We should pre-process this OR do it here. 
    // Let's assume passed 'data.rooms' contains ALL rooms, so we filter here.

    const validRooms = React.useMemo(() => {
        if (!data.rooms || !data.images) return [];
        console.log("PDF Document: Checking rooms for content...");
        const roomsWithContent = data.rooms.filter(room => {
            // Check for visible images belonging to this room
            const roomImages = RoomService.getRoomImages(room, data.images || []);
            const hasImages = roomImages.some(img => img.includeInReport !== false);

            // Check for textual content (Description or Notes)
            const hasTextContent =
                (room.description && String(room.description).trim() !== '') ||
                (room.notizen && String(room.notizen).trim() !== '');

            // Room is valid if it has images OR relevant text
            const isValid = hasImages || hasTextContent;

            if (isValid) {
                console.log(`PDF Document: Room '${room.name}' mapped (Images: ${hasImages}, Text: ${hasTextContent}).`);
            }
            return isValid;
        });
        return roomsWithContent.map(room => {
            // Kontakt-Etage hat Vorrang vor gespeichertem room.stockwerk
            const apt = room.apartment || '';
            const contacts = data.contacts || [];
            const match = contacts.find(c =>
                c.name && apt && (
                    c.name.toLowerCase().includes(apt.toLowerCase()) ||
                    apt.toLowerCase().includes(c.name.toLowerCase())
                )
            );
            const floorFromContact = match?.floor && match.floor.trim() ? match.floor.trim() : null;
            return floorFromContact ? { ...room, stockwerk: floorFromContact } : room;
        });
    }, [data.rooms, data.images]);


    return (
        <Document>
            <Page size="A4" style={styles.page} wrap>



                <PDFHeader data={data} />

                <PDFMetaData data={data} />

                {/* Karte und/oder Aussenbild unter den Projektinfos */}
                {(data.staticMapUrl || data.customMapImage || (data.exteriorPhoto && data.exteriorPhoto.startsWith('data:'))) && (
                    <View>
                        <View style={styles.divider} />
                        <View style={{ gap: 6, marginBottom: 6, marginTop: 6 }}>
                            {/* Row 1: Google Map and/or Custom Map */}
                            {(data.staticMapUrl || data.customMapImage) && (
                                <View style={{ flexDirection: 'row', gap: 6 }}>
                                    {data.staticMapUrl && (
                                        <Image
                                            src={data.staticMapUrl}
                                            style={{
                                                flex: (data.customMapImage || (data.exteriorPhoto && !data.customMapImage)) ? 1 : undefined,
                                                width: (data.customMapImage || (data.exteriorPhoto && !data.customMapImage)) ? undefined : '100%',
                                                height: 160,
                                                objectFit: 'cover',
                                                borderRadius: 4,
                                            }}
                                        />
                                    )}
                                    {data.customMapImage && (
                                        <Image
                                            src={data.customMapImage}
                                            style={{
                                                flex: data.staticMapUrl ? 1 : undefined,
                                                width: data.staticMapUrl ? undefined : '100%',
                                                height: 160,
                                                objectFit: 'cover',
                                                borderRadius: 4,
                                            }}
                                        />
                                    )}
                                    {/* Show exterior photo here ONLY if no customMapImage is present (legacy behavior) */}
                                    {!data.customMapImage && data.exteriorPhoto && data.exteriorPhoto.startsWith('data:') && (
                                        <Image
                                            src={data.exteriorPhoto}
                                            style={{
                                                flex: data.staticMapUrl ? 1 : undefined,
                                                width: data.staticMapUrl ? undefined : '100%',
                                                height: 160,
                                                objectFit: 'cover',
                                                borderRadius: 4,
                                            }}
                                        />
                                    )}
                                </View>
                            )}

                            {/* Row 2: Exterior Photo (Full width if customMapImage is present) */}
                            {data.customMapImage && data.exteriorPhoto && data.exteriorPhoto.startsWith('data:') && (
                                <Image
                                    src={data.exteriorPhoto}
                                    style={{
                                        width: '100%',
                                        height: 160,
                                        objectFit: 'cover',
                                        borderRadius: 4,
                                    }}
                                />
                            )}
                        </View>
                        <View style={styles.divider} />
                    </View>
                )}


                <DescriptionSection data={data} />



                {/* Raumdokumentation Section */}
                <RoomDocumentation rooms={validRooms} images={data.images} contacts={data.contacts} />



                <PlansSection data={data} />



                <CauseSection data={data} />

                <MeasuresSection data={data} />

                <MeasurementsSection data={data} />

                <DataLoggerSection data={data} />

                <PDFFooter data={data} />

            </Page>
        </Document >
    );
};

export default DamageReportDocument;
