/* ==========================================================================
   AI-ASSISTANT LOCK: DO NOT EDIT THIS FILE OR ITS LOGIC WITHOUT EXPLICIT 
   PERMISSION FROM THE USER. THIS APPLIES TO CORE/CRITICAL LOGIC.
   ========================================================================== */
/**
 * OneDriveService.js
 * Microsoft Graph API Integration für QTool
 *
 * Ordnerstruktur: OneDrive/QTool/[Projektnr]_[Strasse]_[Ort]/
 */

import { getGraphAccessToken } from '../lib/onedrive/auth.js';

const GRAPH_BASE = 'https://graph.microsoft.com/v1.0';
const ROOT_FOLDER = 'QTool';

function rejectDirectMutation(kind) {
  throw new Error(`Direkter OneDrive-${kind} ist deaktiviert. Datei lokal registrieren und über den zentralen Storage-/Firmen-Drive-Worker synchronisieren.`);
}

// ─── Token ───────────────────────────────────────────────────────────────────

/**
 * Liefert ein frisches Access-Token über die zentrale auth.js.
 * Gibt null zurück wenn kein Account angemeldet (kein Wurf).
 */
async function getAccessToken() {
  try {
    return await getGraphAccessToken();
  } catch {
    return null;
  }
}

// ─── Hilfsfunktionen ─────────────────────────────────────────────────────────

/**
 * Projektnummer + Adresse → sicherer Ordnername
 * z.B. "20260236_Musterstrasse5_Zuerich"
 */
export function buildProjectFolderName(projectNumber, formData) {
  const street = (formData?.street || formData?.schadenort?.strasse_nr || '').trim();
  const city   = (formData?.city   || formData?.schadenort?.ort         || '').trim();

  const safe = (str) => str
    .replace(/ä/g, 'ae').replace(/ö/g, 'oe').replace(/ü/g, 'ue')
    .replace(/Ä/g, 'Ae').replace(/Ö/g, 'Oe').replace(/Ü/g, 'Ue')
    .replace(/ß/g, 'ss')
    .replace(/[^a-zA-Z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '');

  const parts = [projectNumber, safe(street), safe(city)].filter(Boolean);
  return parts.join('_');
}

// ─── Öffentliche API ─────────────────────────────────────────────────────────

/**
 * Projektordner + Unterordner anlegen
 */
export async function ensureProjectFolders(folderName) {
  void folderName;
  rejectDirectMutation('Ordner-Schreibzugriff');
}

/**
 * PDF-Bericht hochladen
 * @param {string} folderName   Projektordner-Name
 * @param {string} reportType   'Schadensbericht' | 'Trockenbericht'
 * @param {Blob}   blob
 */
export async function uploadReport(folderName, reportType, blob) {
  void folderName;
  void reportType;
  void blob;
  throw new Error('Direkter PDF-Upload zu OneDrive ist deaktiviert. Bericht zuerst lokal registrieren und über den zentralen Storage-/OneDrive-Worker synchronisieren.');
}

/**
 * Bild hochladen
 * @param {string} folderName   Projektordner-Name
 * @param {string} projectNr    Projektnummer für Dateiprefix
 * @param {string} subFolder    Raumname | 'Ursache' | 'Aussenbild'
 * @param {number} index        Laufnummer
 * @param {Blob}   blob
 * @param {string} ext          'jpg' | 'png'
 */
export async function uploadPhoto(folderName, projectNr, subFolder, index, blob, ext = 'jpg') {
  void folderName; void projectNr; void subFolder; void index; void blob; void ext;
  rejectDirectMutation('Foto-Upload');
}

/**
 * Bild hochladen — vereinfachte Version direkt mit File-Objekt
 * Dateiname: [subFolder]_[timestamp].[ext]
 */
export async function uploadPhotoFile(folderName, subFolder, file) {
  void folderName; void subFolder; void file;
  rejectDirectMutation('Foto-Upload');
}

/**
 * Bild hochladen UND sofort nutzbare URL zurückgeben
 * Ersetzt Supabase Storage für neue Fotos.
 * @returns {{ itemId, odPath, downloadUrl }} oder null bei Fehler
 */
export async function uploadPhotoAndGetUrl(folderName, subFolder, file) {
  void folderName; void subFolder; void file;
  rejectDirectMutation('Foto-Upload');
}


/**
 * Frische Download-URL für ein gespeichertes OneDrive-Item holen
 * (wird beim Laden älterer Projekte verwendet)
 * @param {string} itemId  OneDrive Drive Item ID
 */
export async function getPhotoDownloadUrl(itemId) {
  const token = await getAccessToken();
  if (!token || !itemId) return null;
  try {
    const res = await fetch(
      `${GRAPH_BASE}/me/drive/items/${itemId}?$select=id,@microsoft.graph.downloadUrl`,
      { headers: { Authorization: `Bearer ${token}` } }
    );
    if (!res.ok) return null;
    const data = await res.json();
    return data['@microsoft.graph.downloadUrl'] || null;
  } catch {
    return null;
  }
}


/**
 * Excel-Protokoll hochladen
 */
export async function uploadExcel(folderName, blob) {
  void folderName; void blob;
  rejectDirectMutation('Excel-Upload');
}

/**
 * E-Mail-Text als .txt ablegen
 */
export async function uploadMailText(folderName, text) {
  void folderName; void text;
  rejectDirectMutation('Mail-Upload');
}

/**
 * Dokument (Plan, Rechnung, etc.) hochladen
 * @param {string} subFolder  'Plaene' | 'Lieferantenrechnungen'
 */
export async function uploadDocument(folderName, subFolder, fileName, blob) {
  void folderName; void subFolder; void fileName; void blob;
  rejectDirectMutation('Dokument-Upload');
}

/**
 * Projektdaten als JSON sichern (automatisch beim Speichern)
 * Bilder-Blobs (base64/blob-URLs) werden herausgefiltert.
 */
export async function uploadProjectJson(folderName, projectData) {
  void folderName;
  void projectData;
  throw new Error('Direktes Projektdaten-JSON zu OneDrive ist deaktiviert. Supabase-Snapshot und Medien werden ausschließlich über den zentralen Offline-Outbox-/Worker-Nachweis bestätigt.');
}

/**
 * Web-URL des QTool-Hauptordners auf OneDrive zurückgeben
 * → Wird für den "Zu OneDrive" Button im Dashboard genutzt
 */
export async function getQToolFolderWebUrl() {
  const token = await getAccessToken();
  if (!token) return null;
  try {
    const res = await fetch(`${GRAPH_BASE}/me/drive/root:/${ROOT_FOLDER}`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    if (!res.ok) return null;
    const data = await res.json();
    return data.webUrl || null;
  } catch {
    return null;
  }
}
