/* ==========================================================================
   AI-ASSISTANT LOCK: DO NOT EDIT THIS FILE OR ITS LOGIC WITHOUT EXPLICIT 
   PERMISSION FROM THE USER. THIS APPLIES TO CORE/CRITICAL LOGIC.
   ========================================================================== */
/**
 * RoomService.js
 * 
 * Zentrale Logik für das Raum-Management (Rooms).
 * Bereitet Funktionen vor, um die über das System verteilte Logik zu zentralisieren.
 */

export const RoomService = {
    /**
     * Erstellt ein neues, valides Raum-Objekt.
     * @param {Object} params - Die Parameter für den neuen Raum (name, apartment, stockwerk)
     * @returns {Object} Das neue Room-Objekt
     */
    createRoom: (params = {}) => {
        const { name, apartment, stockwerk } = params;
        return {
            id: Date.now(),
            name: name || 'Unbenannter Raum',
            apartment: apartment || '',
            stockwerk: stockwerk || '',
            measurementData: null,
            measurementHistory: []
        };
    },

    /**
     * Normalisiert einen Raumnamen (entfernt "Sonstiges" Präfixe etc.)
     * @param {string} name - Der rohe Name
     * @returns {string} Der normalisierte Name
     */
    normalizeRoomName: (name) => {
        if (!name) return 'Unbenannter Raum';
        let cleanName = name.trim();
        if (cleanName === "Sonstiges / Eigener Name" || cleanName === "Sonstiges") {
            return 'Unbenannter Raum';
        }
        return cleanName;
    },

    /**
     * Aktualisiert einen Raum in einer Liste von Räumen.
     * @param {Array} rooms - Die aktuelle Liste der Räume
     * @param {string|number} roomId - Die ID des zu aktualisierenden Raums
     * @param {Object} updates - Die zu setzenden Felder
     * @returns {Array} Die neue Liste der Räume
     */
    updateRoom: (rooms, roomId, updates) => {
        if (!Array.isArray(rooms)) return [];
        return rooms.map(room => 
            room.id === roomId ? { ...room, ...updates } : room
        );
    },

    /**
     * Entfernt einen Raum aus der Liste.
     * @param {Array} rooms - Die aktuelle Liste der Räume
     * @param {string|number} roomId - Die ID des zu löschenden Raums
     * @returns {Array} Die neue Liste der Räume
     */
    removeRoom: (rooms, roomId) => {
        if (!Array.isArray(rooms)) return [];
        return rooms.filter(room => room.id !== roomId);
    },

    /**
     * Findet alle Bilder, die einem spezifischen Raum zugeordnet sind.
     * Berücksichtigt sowohl die ID-Verknüpfung als auch den Namens-Fallback.
     * @param {Object} room - Der Raum-Obekt
     * @param {Array} images - Die globale Liste der Bilder (formData.images)
     * @returns {Array} Die gefilterten Bilder
     */
    getRoomImages: (room, images) => {
        if (!room || !Array.isArray(images)) return [];
        const roomId = room.id ? String(room.id) : null;
        const roomName = room.name ? String(room.name).trim().toLowerCase() : '';

        return images.filter(img => {
            if (img.roomId) {
                return String(img.roomId) === roomId;
            }
            const assignedTo = img.assignedTo ? String(img.assignedTo).trim().toLowerCase() : '';
            return assignedTo === roomName;
        });
    },

    /**
     * Reichert Räume mit Etagen-Informationen aus der Kontaktliste an.
     * (Logik aus PDFService extrahiert für allgemeine Nutzung)
     * @param {Array} rooms - Die Liste der Räume
     * @param {Array} contacts - Die Liste der Kontakte (formData.contacts)
     * @returns {Array} Die angereicherten Räume
     */
    enrichRooms: (rooms, contacts) => {
        if (!Array.isArray(rooms)) return [];
        const liveContacts = contacts || [];
        
        return rooms.map(room => {
            // Wenn bereits ein Stockwerk vorhanden ist, dieses behalten
            if (room.stockwerk && room.stockwerk.trim() !== '') return room;

            const apt = (room.apartment || '').toLowerCase().trim();
            if (!apt) return room;

            const match = liveContacts.find(c => {
                const cn = (c.name || '').toLowerCase().trim();
                return cn && apt && (cn.includes(apt) || apt.includes(cn));
            });

            const floor = (match?.floor || '').trim();
            return floor ? { ...room, stockwerk: floor } : room;
        });
    },

    /**
     * Integriert Messdaten in die Raumstruktur inkl. Historie-Management.
     * @param {Array} rooms - Die aktuelle Liste der Räume
     * @param {string|number} roomId - Die ID des Zielraums
     * @param {Object} measurementData - Die neuen Messdaten (measurements, globalSettings, canvasImage, etc.)
     * @param {boolean} isNewSequence - Ob eine neue Messreihe (Historie) erstellt werden soll
     * @returns {Array} Die aktualisierte Liste der Räume
     */
    syncMeasurement: (rooms, roomId, measurementData, isNewSequence = false) => {
        if (!Array.isArray(rooms)) return [];
        
        return rooms.map(r => {
            if (r.id !== roomId) return r;

            const history = r.measurementHistory ? [...r.measurementHistory] : [];
            const updatedHistory = (isNewSequence && r.measurementData?.measurements?.length > 0)
                ? [...history, {
                    id: `hist_${Date.now()}`,
                    date: r.measurementData.globalSettings?.date || new Date().toISOString(),
                    measurements: r.measurementData.measurements.map(m => ({ ...m })),
                    globalSettings: { ...(r.measurementData.globalSettings || {}) },
                    canvasImage: r.measurementData.canvasImage,
                    protocolUrl: r.measurementData.protocolUrl,
                    galleryPhotos: r.measurementData.galleryPhotos || []
                }]
                : history;

            return { 
                ...r, 
                name: measurementData.globalSettings?.room || r.name, 
                apartment: measurementData.globalSettings?.apartment || r.apartment, 
                measurementData: { ...measurementData }, 
                measurementHistory: updatedHistory 
            };
        });
    }
};
