/* ==========================================================================
   AI-ASSISTANT LOCK: DO NOT EDIT THIS FILE OR ITS LOGIC WITHOUT EXPLICIT 
   PERMISSION FROM THE USER. THIS APPLIES TO CORE/CRITICAL LOGIC.
   ========================================================================== */
import React from 'react';
import { View, Image, Text } from '@react-pdf/renderer';
import { styles } from '../PDFStyles';
import ImageGrid from '../components/ImageGrid';

const DescriptionSection = ({ data }) => {
    const allUnassignedImages = data.images ? data.images.filter(img => !img.roomId && img.assignedTo !== 'Schadenfotos' && img.assignedTo !== 'Pläne' && img.assignedTo !== 'Messprotokolle' && img.includeInReport !== false) : [];
    const unassignedImages = allUnassignedImages
        .filter(img => !img.linkedToOriginal)
        .map(img => {
            const thermal = img.id ? allUnassignedImages.find(i => i.linkedToOriginal === img.id) : null;
            return thermal ? { ...img, thermalImage: thermal } : img;
        });

    const hasUnassignedImages = unassignedImages.length > 0;
    const hasDescription = data.description && data.description.trim().length > 0 && data.includeDescriptionInReport !== false;

    if (!hasDescription && !hasUnassignedImages) return null;

    const firstImages = unassignedImages.slice(0, 2);
    const restImages = unassignedImages.slice(2);

    return (
        <View style={{ marginBottom: 15 }}>
            {/* Header + first image pair: wrap=false keeps them together */}
            <View wrap={false}>
                <View style={styles.divider} />
                
                {hasDescription && (
                    <>
                        <Text style={styles.sectionTitle}>SCHADENBESCHREIBUNG</Text>
                        <Text style={styles.textBlock}>{data.description.trim()}</Text>
                    </>
                )}

                {firstImages.length > 0 && (
                    <ImageGrid images={firstImages} />
                )}
            </View>

            {/* Remaining images can flow freely */}
            {restImages.length > 0 && (
                <ImageGrid images={restImages} />
            )}
        </View>
    );
};

export default DescriptionSection;
