/* ==========================================================================
   AI-ASSISTANT LOCK: DO NOT EDIT THIS FILE OR ITS LOGIC WITHOUT EXPLICIT 
   PERMISSION FROM THE USER. THIS APPLIES TO CORE/CRITICAL LOGIC.
   ========================================================================== */
import React from 'react';
import { View, Text } from '@react-pdf/renderer';
import { styles } from '../PDFStyles';

const MeasuresSection = ({ data }) => {
    const hasMeasures = data.measures || (data.selectedMeasures && data.selectedMeasures.length > 0);

    if (!hasMeasures) return null;

    return (
        <View style={{ marginBottom: 15 }} break={true}>
            <View wrap={false}>
                <View style={styles.divider} />
                <Text style={styles.sectionTitle}>MASSNAHMEN</Text>
            </View>
            {data.selectedMeasures && data.selectedMeasures.length > 0 && (
                <View style={{ marginBottom: data.measures ? 10 : 0 }}>
                    {data.selectedMeasures.map((measure, idx) => (
                        <View key={idx} style={{ marginBottom: 8 }} wrap={false}>
                            <Text style={styles.roomHeader}>{measure.toUpperCase()}</Text>
                            {data.measureNotes && data.measureNotes[measure] && (
                                <Text style={styles.textBlock}>{data.measureNotes[measure]}</Text>
                            )}
                        </View>
                    ))}
                </View>
            )}
            {data.measures && (
                <View style={{ marginTop: 5 }} wrap={false}>
                    <Text style={styles.roomHeader}>ZUSÄTZLICHE MASSNAHMEN</Text>
                    <Text style={styles.textBlock}>{data.measures}</Text>
                </View>
            )}
        </View>
    );
};

export default MeasuresSection;
