/* ==========================================================================
   AI-ASSISTANT LOCK: DO NOT EDIT THIS FILE OR ITS LOGIC WITHOUT EXPLICIT 
   PERMISSION FROM THE USER. THIS APPLIES TO CORE/CRITICAL LOGIC.
   ========================================================================== */
import React from 'react';
import { View, Image, Text } from '@react-pdf/renderer';
import { styles } from '../PDFStyles';

const PDFHeader = ({ data }) => {
    return (
        <View style={styles.header}>
            <View style={{ alignItems: 'flex-start' }}>
                <Image src="/1080p.jpg" style={styles.logo} />
                {data.projectNumber && (
                    <Text
                        style={{ fontSize: 9, color: '#0F6EA3', fontWeight: 'bold', marginTop: 2 }}
                        render={({ pageNumber }) => (
                            pageNumber > 1 ? `Projekt-Nr: ${data.projectNumber}` : ''
                        )}
                    />
                )}
                {data.orderNumber && (
                    <Text
                        style={{ fontSize: 8, color: '#64748B', fontWeight: 'bold' }}
                        render={({ pageNumber }) => (
                            pageNumber > 1 ? `Auftrag: ${data.orderNumber}` : ''
                        )}
                    />
                )}
            </View>
            <View style={styles.companyInfo}>
                <Text>Q-Service AG</Text>
                <Text>Kriesbachstrasse 30</Text>
                <Text>8600 Dübendorf</Text>
                <Text>www.q-service.ch</Text>
            </View>
        </View>
    );
};

export default PDFHeader;
