/* ==========================================================================
   AI-ASSISTANT LOCK: DO NOT EDIT THIS FILE OR ITS LOGIC WITHOUT EXPLICIT 
   PERMISSION FROM THE USER. THIS APPLIES TO CORE/CRITICAL LOGIC.
   ========================================================================== */
import { useState, useEffect, useCallback, useRef } from 'react'
import { useSessionLock } from './hooks/useSessionLock'
import { Plus, LayoutDashboard, Settings, User, Users, LogOut, Thermometer, Database, RotateCcw, Download, Sun, Moon } from 'lucide-react'
import { supabase } from './supabaseClient'
import Dashboard from './components/Dashboard'
import DamageForm from './components/DamageForm'
import DeviceManager from './components/DeviceManager'
import UserManagementModal from './components/UserManagementModal'
import MeasurementDeviceManager from './components/MeasurementDeviceManager'
import LoginScreen from './components/LoginScreen'
import EmailImportModalV2 from './components/EmailImportModalV2'
import i18n from './i18n'
import { buildProjectFolderName, uploadProjectJson } from "./services/OneDriveService";

function sanitizeMeasurementStorage(reportData) {
  if (!reportData || !Array.isArray(reportData.rooms)) return reportData;

  const normalize = (val) => String(val || '').trim().toLowerCase().replace(/-/g, ' ').replace(/\s+/g, ' ');

  let updatedMeasurementRooms = Array.isArray(reportData.measurementRooms) ? [...reportData.measurementRooms] : [];
  let updatedRooms = [];

  for (const r of reportData.rooms) {
    const hasMeasurementData = r.measurementData || r.measurementHistory || r.measurements || r.measurementPoints || r.points;

    if (hasMeasurementData) {
      const normApt = normalize(r.apartment || 'Allgemeiner Bereich');
      const normName = normalize(r.name || 'Unbenannter Raum');

      const existingIdx = updatedMeasurementRooms.findIndex(mr => 
        normalize(mr.apartment || 'Allgemeiner Bereich') === normApt &&
        normalize(mr.name || 'Unbenannter Raum') === normName
      );

      if (existingIdx >= 0) {
        const existingRoom = updatedMeasurementRooms[existingIdx];
        if (!existingRoom.measurementHistory && r.measurementHistory) existingRoom.measurementHistory = r.measurementHistory;
        if (!existingRoom.measurementData && r.measurementData) existingRoom.measurementData = r.measurementData;
        if (!existingRoom.canvasImage && r.canvasImage) existingRoom.canvasImage = r.canvasImage;
      } else {
        updatedMeasurementRooms.push({
          id: r.id || `room_${Date.now()}`,
          name: r.name,
          apartment: r.apartment,
          stockwerk: r.stockwerk,
          measurementData: r.measurementData,
          measurementHistory: r.measurementHistory,
          measurements: r.measurements,
          measurementPoints: r.measurementPoints,
          points: r.points,
          canvasImage: r.canvasImage,
          sketch: r.sketch
        });
      }
    }

    const hasRealRoomData = (r.photos && r.photos.length > 0) || (r.damages && r.damages.length > 0) || (r.equipment && r.equipment.length > 0) || r.construction || r.notes;

    if (hasRealRoomData || !hasMeasurementData) {
      const cleanRoom = { ...r };
      delete cleanRoom.measurementData;
      delete cleanRoom.measurementHistory;
      delete cleanRoom.measurements;
      delete cleanRoom.measurementPoints;
      delete cleanRoom.points;
      updatedRooms.push(cleanRoom);
    }
  }

  return {
    ...reportData,
    rooms: updatedRooms,
    measurementRooms: updatedMeasurementRooms
  };
}

function App() {
  // Neuer Tab = neue sessionStorage → startet immer auf Dashboard
  // damit nicht alle Tabs dasselbe Projekt aus localStorage öffnen
  const _isNewTab = !sessionStorage.getItem('qtool_tab_init');
  if (_isNewTab) sessionStorage.setItem('qtool_tab_init', '1');

  const [view, setView] = useState(() => {
    if (_isNewTab) return 'dashboard';
    return localStorage.getItem('qservice_current_view') || 'dashboard';
  });

  const [selectedReport, setSelectedReport] = useState(() => {
    if (_isNewTab) return null; // Neuer Tab startet ohne offenes Projekt
    const savedId = localStorage.getItem('qservice_selected_report_id');
    const savedReports = localStorage.getItem('qservice_reports_prod');
    if (savedId && savedReports) {
      try {
        const reports = JSON.parse(savedReports);
        return reports.find(r => r.id === savedId) || null;
      } catch (e) {
        return null;
      }
    }
    return null;
  });

  // Authentication / User Management State
  const [showUserModal, setShowUserModal] = useState(false);
  const [showMeasurementManager, setShowMeasurementManager] = useState(false);
  const [currentUser, setCurrentUser] = useState({ id: 1, name: 'Admin User', role: 'admin' }); // Auto-login as admin
  const sessionTokenRef = useRef(null);
  const isSessionActiveRef = useRef(true);
  const selectedReportRef = useRef(null);
  const sessionStartedAtRef = useRef(Date.now());

  // Session-Token: einmalig pro Tab (sessionStorage)
  const [mySessionToken] = useState(() => {
    let t = sessionStorage.getItem('qtool_session_token');
    if (!t) {
      t = crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
      sessionStorage.setItem('qtool_session_token', t);
    }
    sessionTokenRef.current = t;
    return t;
  });
  const myDevice = /iPad|iPhone|Android/i.test(navigator.userAgent) ? 'Mobil' : 'Desktop';

  // Refs synchron halten
  useEffect(() => { selectedReportRef.current = selectedReport; }, [selectedReport]);

  // ── State-Deklarationen ───────────────────────────────────────────────────
  const [userRole, setUserRole] = useState('admin'); // 'admin' | 'technician' | 'user'
  const [isTechnicianMode, setIsTechnicianMode] = useState(false); // Globaler Fallback-Modus (Dashboard)
  const [supabaseStatus, setSupabaseStatus] = useState(null); // null | { ok: bool, count: number, error: string }

  // ── Dark / Light Mode ────────────────────────────────────────────────────
  const [isDarkMode, setIsDarkMode] = useState(() => {
    const saved = localStorage.getItem('qtool_dark_mode');
    return saved !== null ? saved === 'true' : false; // Default: Light
  });

  useEffect(() => {
    document.documentElement.setAttribute('data-theme', isDarkMode ? 'dark' : 'light');
    localStorage.setItem('qtool_dark_mode', String(isDarkMode));
  }, [isDarkMode]);

  // Projektspezifischer Modus: 'desktop' | 'technician' (Mutex – nie beides gleichzeitig)
  const [projectMode, setProjectMode] = useState('desktop');
  const setProjectModeExclusive = (mode) => {
    if (mode !== 'desktop' && mode !== 'technician') return;
    setProjectMode(mode);
  };
  // Effektiver Modus: Im Projekt-View gilt projectMode, im Dashboard isTechnicianMode
  const effectiveMode = (view === 'details' || view === 'new-report') ? projectMode : (isTechnicianMode ? 'technician' : 'desktop');

  const [showEmailImport, setShowEmailImport] = useState(false);
  const [audioDevices, setAudioDevices] = useState([]);
  const [selectedDeviceId, setSelectedDeviceId] = useState(localStorage.getItem('qtool_selected_mic') || '');

  // ── Sync-Status (Variante C: kein MSAL, kein direkter OneDrive-Login) ──────
  // Zählt ausstehende lokale Fotos direkt aus IndexedDB (qtool-photos)
  const [syncStatus, setSyncStatus] = useState('idle'); // 'idle' | 'syncing' | 'error'
  const [syncPending, setSyncPending] = useState(0);

  // Ausstehende lokale Bilder zählen – alle 10s aktualisieren
  // Fällt automatisch auf 0 nach erfolgreichem Supabase-Upload
  useEffect(() => {
    const countPending = () => new Promise((resolve) => {
      const req = indexedDB.open('qtool-photos');
      req.onsuccess = () => {
        const db = req.result;
        if (!db.objectStoreNames.contains('photos')) { resolve(0); return; }
        const tx  = db.transaction('photos', 'readonly');
        const all = tx.objectStore('photos').getAll();
        all.onsuccess = () => resolve(
          (all.result || []).filter(p =>
            p.syncStatus !== 'synced' && !p.oneDriveItemId
          ).length
        );
        all.onerror = () => resolve(0);
      };
      req.onerror = () => resolve(0);
      req.onupgradeneeded = () => resolve(0);
    });

    countPending().then(setSyncPending).catch(() => {});
    const interval = setInterval(() => {
      countPending().then(setSyncPending).catch(() => {});
    }, 10_000);
    return () => clearInterval(interval);
  }, []);

  // ======================================================
  // ======================================================
  // QTOOL – REST-basiertes Session-Locking (kein WebSocket)
  // Polling über Supabase REST – funktioniert überall
  // ======================================================

  const resolvedProjectMode = projectMode === 'technician' ? 'technician' : 'desktop';

  const { lockedProjectIds, isSessionActive, setIsSessionActive, takeOverLock } = useSessionLock(
    supabase,
    mySessionToken,
    selectedReport?.id ?? null,
    view,
    resolvedProjectMode,
    sessionStartedAtRef.current
  );

  // isSessionActive-Ref synchron halten (für handleSaveReport)
  useEffect(() => { isSessionActiveRef.current = isSessionActive; }, [isSessionActive]);

  // UI-Sperr-Variablen
  // Im Techniker-Modus ist der Lock komplett deaktiviert — Techniker arbeiten immer im Feld
  const isLockedByOtherMode = (projectMode === 'technician' || isTechnicianMode) ? false : !isSessionActive;
  const isReadOnly = isLockedByOtherMode;
  const sessionLockMessage = isLockedByOtherMode
    ? 'Dieses Projekt ist aktuell im anderen Modus geöffnet und kann hier momentan nicht bearbeitet werden.'
    : '';



  // iOS-Tastatur: Eingabefeld automatisch sichtbar halten (Techniker-Modus)
  useEffect(() => {
    if (!isTechnicianMode) return;

    let focusedEl = null;

    // Nächsten scrollbaren Vorfahren finden (Modal-Body oder window)
    const getScrollParent = (el) => {
      let node = el.parentElement;
      while (node) {
        const style = window.getComputedStyle(node);
        const overflow = style.overflowY;
        if ((overflow === 'auto' || overflow === 'scroll') && node.scrollHeight > node.clientHeight) {
          return node;
        }
        node = node.parentElement;
      }
      return null;
    };

    const scrollElIntoView = (el) => {
      if (!el) return;
      const viewportHeight = window.visualViewport ? window.visualViewport.height : window.innerHeight;
      const rect = el.getBoundingClientRect();
      if (rect.bottom > viewportHeight - 20) {
        const scrollParent = getScrollParent(el);
        if (scrollParent) {
          const parentRect = scrollParent.getBoundingClientRect();
          const offset = rect.bottom - parentRect.top - scrollParent.clientHeight + 80;
          scrollParent.scrollBy({ top: offset, behavior: 'smooth' });
        } else {
          window.scrollBy({ top: rect.bottom - viewportHeight + 80, behavior: 'smooth' });
        }
      }
    };

    const handleFocus = (e) => {
      const el = e.target;
      if (el.tagName !== 'INPUT' && el.tagName !== 'TEXTAREA' && el.tagName !== 'SELECT') return;
      focusedEl = el;
      // Sofort + nach Tastatur-Animation scrollen
      setTimeout(() => scrollElIntoView(el), 100);
      setTimeout(() => scrollElIntoView(el), 500);
    };

    const handleBlur = (e) => {
      const el = e.target;
      if (el.tagName !== 'INPUT' && el.tagName !== 'TEXTAREA' && el.tagName !== 'SELECT') return;
      focusedEl = null;
    };

    // Feuert wenn iOS-Tastatur fertig erschienen ist (zuverlässiger als Timeout)
    const handleViewportResize = () => {
      if (focusedEl) {
        setTimeout(() => scrollElIntoView(focusedEl), 50);
      }
    };

    document.addEventListener('focusin', handleFocus);
    document.addEventListener('focusout', handleBlur);
    if (window.visualViewport) {
      window.visualViewport.addEventListener('resize', handleViewportResize);
    }

    return () => {
      document.removeEventListener('focusin', handleFocus);
      document.removeEventListener('focusout', handleBlur);
      if (window.visualViewport) {
        window.visualViewport.removeEventListener('resize', handleViewportResize);
      }
    };
  }, [isTechnicianMode]);


  // Users List (Managed here to share with LoginScreen)
  const [users, setUsers] = useState(() => {
    const saved = localStorage.getItem('qtool_users_v2');
    return saved ? JSON.parse(saved) : [
      { id: 1, name: 'Admin User', role: 'admin', password: 'admin' },
      { id: 2, name: 'Techniker 1', role: 'technician', password: '123' }
    ];
  });

  // Persist users changes
  useEffect(() => {
    localStorage.setItem('qtool_users_v2', JSON.stringify(users));
  }, [users]);

  const handleLogin = (user) => {
    setCurrentUser(user);
    setUserRole(user.role);
    // Automatically set mode based on role
    setIsTechnicianMode(user.role === 'technician');
    // Projektmodus beim Login zurücksetzen
    setProjectMode(user.role === 'technician' ? 'technician' : 'desktop');
    showToast(`Angemeldet als ${user.name}`, 'success');
  };

  const handleLogout = () => {
    setCurrentUser(null);
    setUserRole('admin');
    setIsTechnicianMode(false);
    setProjectMode('desktop');
    setView('dashboard');
    setSelectedReport(null);
  };

  // Initialize reports from LocalStorage
  const [reports, setReports] = useState(() => {
    const saved = localStorage.getItem('qservice_reports_prod');
    if (saved) {
      try {
        return JSON.parse(saved);
      } catch (e) {
        console.error("Failed to parse reports from local storage", e);
      }
    }
    return [];
  });

  // Persist view and selected report state
  useEffect(() => {
    localStorage.setItem('qservice_current_view', view);
    if (selectedReport && selectedReport.id) {
      localStorage.setItem('qservice_selected_report_id', selectedReport.id);
    } else {
      localStorage.removeItem('qservice_selected_report_id');
    }
  }, [view, selectedReport]);




  // Fetch reports from Supabase on mount
  useEffect(() => {
    if (!supabase) {
      setSupabaseStatus({ ok: false, count: 0, error: 'Supabase nicht konfiguriert (kein Client)' });
      return;
    }

    const fetchReports = async () => {
      setSupabaseStatus({ ok: null, count: null, error: null }); // Laden...
      try {
        const { data, error } = await supabase
          .from('damage_reports')
          .select('report_data, updated_at');
          // HINWEIS: Client-seitige Sortierung um Statement Timeout bei großen JSONs zu verhindern

        if (error) {
          console.error('[Supabase] Fehler beim Laden:', error);
          setSupabaseStatus({ ok: false, count: 0, error: `${error.code}: ${error.message}` });
        } else if (data) {
          const loadedReports = data
            // Sortierung auf dem Client um DB Statement Timeouts zu vermeiden
            .sort((a, b) => new Date(b.report_data?.date || b.updated_at).getTime() - new Date(a.report_data?.date || a.updated_at).getTime())
            .map(row => ({
            ...row.report_data,
            _supabase_updated_at: row.updated_at,
            images: (row.report_data.images || []).map(img => ({
              ...img,
              includeInReport: img.includeInReport !== false
            }))
          })).filter(r => !r._isSession && !r.deleted_at); // Session + soft-deleted ausblenden

          console.log(`[Supabase] ${loadedReports.length} Projekte geladen (${data.length} DB-Einträge gesamt).`);
          console.log('[MEASROOM TRACE] fetchReports loaded', {
             measurementRoomsLength: loadedReports[0]?.measurementRooms?.length,
             names: loadedReports[0]?.measurementRooms?.map(r=>r.name)
          });
          setSupabaseStatus({ ok: true, count: loadedReports.length, total: data.length, error: null });

          if (loadedReports.length > 0) {
            setReports(loadedReports);
            try {
              const cachedReports = loadedReports.slice(0, 10).map(r => ({
                ...r,
                damageTypeImage: (r.damageTypeImage && r.damageTypeImage.startsWith('data:')) ? null : r.damageTypeImage,
                exteriorPhoto: (r.exteriorPhoto && r.exteriorPhoto.startsWith('data:')) ? null : r.exteriorPhoto,
                images: r.images ? r.images.map(img => ({
                  ...img,
                  preview: (img.preview && (img.preview.startsWith('blob:') || img.preview.startsWith('data:'))) ? null : img.preview
                })) : []
              }));
              localStorage.setItem('qservice_reports_prod', JSON.stringify(cachedReports));
            } catch (e) {
              console.warn('LocalStorage cache fehlgeschlagen:', e.message);
            }
          }
        }
      } catch (e) {
        console.error('[Supabase] Unerwarteter Fehler:', e);
        setSupabaseStatus({ ok: false, count: 0, error: `Unerwarteter Fehler: ${e.message}` });
      }
    };

    fetchReports();
  }, []);

  const handleSelectReport = async (report) => {
    setSelectedReport(report);
    setView('details');
    setIsSessionActive(true);
    // Projektspezifischen Modus laden
    const savedMode = report?._projectMode;
    const initialMode = (savedMode === 'technician' || savedMode === 'desktop')
      ? savedMode
      : (isTechnicianMode ? 'technician' : 'desktop');
    setProjectMode(initialMode);
  }

  const handleCancelEntry = () => {
    setView('dashboard');
    setSelectedReport(null);
    setIsSessionActive(true);
  }

  const handleSaveReport = useCallback(async (updatedReport, silent = false) => {
    let finalReport = sanitizeMeasurementStorage({ ...updatedReport });
    
    console.log('[MEAS STORAGE GUARD]', {
        roomsLength: finalReport.rooms?.length,
        measurementRoomsLength: finalReport.measurementRooms?.length,
        measurementNames: finalReport.measurementRooms?.map(r => r.name),
        roomsWithMeasurementData: finalReport.rooms?.filter(r => r.measurementData || r.measurementHistory)?.length
    });

    console.log('[MEASROOM TRACE] App handleSaveReport incoming', {
        measurementRoomsLength: finalReport.measurementRooms?.length,
        names: finalReport.measurementRooms?.map(r => r.name)
    });

    if (!finalReport.id) {
      // Immer UUID verwenden — verhindert ID-Kollisionen die zu Datenverlust führen
      finalReport.id = (typeof crypto !== 'undefined' && crypto.randomUUID)
        ? crypto.randomUUID()
        : `TMP-${Date.now()}-${Math.random().toString(36).slice(2)}`;
    }
    if (!finalReport.date) finalReport.date = new Date().toISOString();

    setReports(currentReports => {
      let newReports;
      const exists = currentReports.find(r => r.id === finalReport.id);

      if (exists) {
        newReports = currentReports.map(r => r.id === finalReport.id ? finalReport : r);
      } else {
        newReports = [finalReport, ...currentReports];
      }

      // 1. Persist to LocalStorage (Shrink if too large)
      try {
        // Only save metadata and limited content to LocalStorage to prevent QuotaExceededError
        // We keep full data in memory and in Supabase
        const minimalReports = newReports.slice(0, 15).map(r => ({
          ...r,
          // Strip heavy image content from LocalStorage
          damageTypeImage: (r.damageTypeImage && r.damageTypeImage.startsWith('data:')) ? null : r.damageTypeImage,
          exteriorPhoto: (r.exteriorPhoto && r.exteriorPhoto.startsWith('data:')) ? null : r.exteriorPhoto,
          images: r.images ? r.images.map(img => ({
            ...img,
            preview: (img.preview && (img.preview.startsWith('blob:') || img.preview.startsWith('data:'))) ? null : img.preview
          })) : []
        }));

        try {
          localStorage.setItem('qservice_reports_prod', JSON.stringify(minimalReports));
        } catch (innerE) {
          if (innerE.name === 'QuotaExceededError') {
            // If still failing, keep only the most recent 5
            localStorage.setItem('qservice_reports_prod', JSON.stringify(minimalReports.slice(0, 5)));
          }
        }
      } catch (e) {
        console.warn("LocalStorage caching failed, but in-memory state remains:", e.message);
      }
      return newReports;
    });

    if (!silent || (!updatedReport.id && finalReport.id)) {
      setSelectedReport(prev => {
        if (!prev || prev.id === finalReport.id || !updatedReport.id) return finalReport;
        return prev;
      });
      if (!silent) setView('details');
    }

    if (supabase) {
      // ── Sitzungsschutz: Kein Supabase-Save wenn anderes Gerät aktiv ist ───────────
      if (!isSessionActiveRef.current) {
        console.warn('[Session] Sitzung inaktiv – Supabase-Save blockiert für:', finalReport.id);
        return finalReport; // Nur lokal im Memory, kein Supabase-Write
      }

      const now = new Date().toISOString();
      // _supabase_updated_at ist ein internes Feld – nicht in die DB speichern
      const { _supabase_updated_at: loadedAt, ...reportForStorage } = finalReport;

      const rowData = {
        id: finalReport.id,
        project_title: finalReport.projectTitle,
        client: finalReport.client,
        address: finalReport.address,
        status: finalReport.status,
        assigned_to: finalReport.assignedTo,
        date: finalReport.date,
        drying_started: finalReport.dryingStarted,
        report_data: reportForStorage,  // ohne _supabase_updated_at
        updated_at: now
      };

      console.log('[MEASROOM TRACE] App final report_data', {
          measurementRoomsLength: reportForStorage.measurementRooms?.length,
          keys: Object.keys(reportForStorage)
      });

      const oneDriveBackup = () => {
        try {
          const odFolder = buildProjectFolderName(
            finalReport.projectNumber || finalReport.id || 'Unbekannt',
            finalReport
          );
          uploadProjectJson(odFolder, finalReport).catch(e =>
            console.warn('[OneDrive] JSON-Backup fehlgeschlagen:', e.message)
          );
        } catch (e) {
          console.warn('[OneDrive] JSON-Backup fehlgeschlagen:', e.message);
        }
      };

      // ─── Konfliktschutz: Nur speichern wenn kein neueres Update existiert ───────
      if (loadedAt && finalReport.id && !finalReport.id.startsWith('TMP-')) {
        const { data: updateResult, error } = await supabase
          .from('damage_reports')
          .update(rowData)
          .eq('id', finalReport.id)
          .lte('updated_at', loadedAt)  // Nur wenn DB-Version ≤ geladene Version
          .select('id');

        if (error) {
          console.log('[MEASROOM TRACE] Supabase update result', { error, data: updateResult });
          console.error('Error saving to Supabase:', error);
          showToast(`⚠️ Speicherfehler: ${error.message || error.code || 'Supabase-Fehler'}. Daten nur lokal gesichert!`, 'error');
        } else if (!updateResult || updateResult.length === 0) {
          console.log('[MEASROOM TRACE] Supabase update result', { error: 'Conflict', data: null });
          // Konflikt: Ein anderes Gerät hat neuere Daten → NICHT überschreiben
          console.warn('[Sync-Konflikt] Neuere Version in Supabase – abgebrochen:', finalReport.id);
          showToast('⚠️ Neuere Version auf anderem Gerät! Seite neu laden.', 'warning');
        } else {
          console.log('[MEASROOM TRACE] Supabase update result', { error: null, data: updateResult });
          // Erfolgreich: _supabase_updated_at aktualisieren damit nächster Save erlaubt ist
          setReports(prev => prev.map(r => r.id === finalReport.id ? { ...r, _supabase_updated_at: now } : r));
          oneDriveBackup();
        }
      } else {
        // Neues Projekt oder kein bekannter Zeitstempel → einfaches Upsert
        supabase.from('damage_reports').upsert(rowData).then(({ data, error }) => {
          console.log('[MEASROOM TRACE] Supabase update result', { error, data });
          if (error) {
            console.error('Error saving to Supabase:', error);
            showToast(`⚠️ Speicherfehler: ${error.message || error.code || 'Supabase-Fehler'}. Daten nur lokal gesichert!`, 'error');
          } else {
            setReports(prev => prev.map(r => r.id === finalReport.id ? { ...r, _supabase_updated_at: now } : r));
            oneDriveBackup();
          }
        });
      }
    }

    return finalReport;
  }, [supabase]);

  const handleNavigateToReport = (identifier) => {
    if (!identifier) return;
    const report = reports.find(r => r.id === identifier || r.projectTitle === identifier || r.projectNumber === identifier);
    if (report) {
      handleSelectReport(report);
      showToast(`Auftrag "${report.projectTitle || report.id}" geöffnet`, 'success');
    } else {
      showToast(`Auftrag "${identifier}" nicht gefunden`, 'error');
    }
  };

  const handleDeleteReport = async (reportId) => {
    const reportToDelete = reports.find(r => r.id === reportId);
    if (!reportToDelete) return;

    // ── Soft-Delete: Projekt aus lokalem State entfernen, aber in DB nur markieren ──
    setReports(prev => {
      const newReports = prev.filter(r => r.id !== reportId);
      try {
        localStorage.setItem('qservice_reports_prod', JSON.stringify(newReports));
      } catch (e) {
        console.error("LocalStorage Update Failed", e);
      }
      return newReports;
    });

    if (selectedReport && selectedReport.id === reportId) {
      setSelectedReport(null);
      setView('dashboard');
    }

    if (supabase) {
      // SOFT-DELETE: Projekt aus DB als gelöscht markieren
      // Spalte deleted_at muss in Supabase existieren – falls nicht, wird nur lokal gelöscht
      try {
        const { error } = await supabase
          .from('damage_reports')
          .update({ deleted_at: new Date().toISOString() })
          .eq('id', reportId);
        if (error) {
          if (error.code === '42703') {
            console.warn('[Soft-Delete] deleted_at Spalte fehlt in DB – nur lokal gelöscht');
            showToast('Projekt lokal gelöscht', 'success');
          } else {
            console.error('[Soft-Delete] Fehler:', error);
            showToast(`Fehler: ${error.message || error.code}`, 'error');
          }
        } else {
          showToast('Projekt gelöscht', 'success');
        }
      } catch (e) {
        console.warn('[Soft-Delete] Exception:', e.message);
        showToast('Projekt lokal gelöscht', 'success');
      }
    } else {
      showToast('Projekt lokal gelöscht', 'success');
    }
  };

  // ── Backup: Alle Projekte als JSON-Datei herunterladen ──────────────────────
  const handleDownloadBackup = async () => {
    try {
      let backupData = reports;
      if (supabase) {
        const { data, error } = await supabase
          .from('damage_reports')
          .select('*');
        if (!error && data) {
            backupData = data.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
        }
      }
      const blob = new Blob(
        [JSON.stringify(backupData, null, 2)],
        { type: 'application/json' }
      );
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `qtool-backup-${new Date().toISOString().slice(0, 10)}.json`;
      a.click();
      URL.revokeObjectURL(url);
      showToast(`✅ Backup gespeichert (${backupData.length} Projekte)`, 'success');
    } catch (e) {
      showToast(`Backup fehlgeschlagen: ${e.message}`, 'error');
    }
  };

  const handleEmailImport = (importedData) => {
    if (!importedData) return;

    const newId = `P-${Date.now()}`;

    // ── V4 Felder (EmailImportModalV2 Parser V4) ──
    const ag = importedData.auftraggeber || {};            // V4
    const av = importedData.auftrag_verwaltung || {};      // V3 Compat
    const rd = importedData.rechnungs_details || {};
    const so = importedData.schadenort || {};
    const pd = importedData.projekt_daten || {};

    // Auftraggeber: V4 hat "firma" + "kontaktperson", V3 hatte "firma" + "ansprechperson"
    const clientFirma = ag.firma || av.firma || '';
    const kontaktperson = ag.kontaktperson || av.ansprechperson || '';

    // Schadenort
    const street = [so.strasse, so.hausnummer].filter(Boolean).join(' ') || so.strasse_nr || '';
    const zip    = so.plz || '';
    const city   = so.ort || '';

    // Projekttitel: V4 hat projektTitel top-level
    const projektTitel = importedData.projektTitel || pd.titel || '';

    // Beschreibung: V4 hat beschreibung top-level, V3 in projekt_daten
    const beschreibung = importedData.beschreibung || pd.beschreibung || '';

    // Referenznummer: in rechnungs_details.referenz (V4) oder projekt_daten (V3)
    const projectNum = rd.referenz || pd.referenz_nummer || pd.erp_id || '';

    // Rollenumwandlung
    const rolleMap = {
      'verwaltung':          'Verwaltung',
      'mieter':              'Mieter',
      'eigentuemer':         'Eigentümer',
      'rechnungsempfaenger': 'Eigentümer',
      'dienstleister':       'Handwerker',
      'handwerker':          'Handwerker',
      'sanitaer':            'Handwerker',
      'dachdecker':          'Handwerker',
      'hauswart':            'Hauswart',
      'sonstiges':           'Mieter',
      'Eigentümer':          'Eigentümer',
      'Verwaltung':          'Verwaltung',
      'Handwerker':          'Handwerker',
      'Hauswart':            'Hauswart',
      'Mieter':              'Mieter',
    };

    const newReport = {
      id: newId,
      projectTitle: projektTitel || projectNum || clientFirma || 'Importiertes Projekt',
      projectNumber: projectNum,
      orderNumber:   pd.auftrags_nr || '',

      // Auftraggeber / Verwaltung
      client:      clientFirma,
      clientStreet: av.adresse || ag.adresse || '',
      clientZip:   av.plz || ag.plz || '',
      clientCity:  av.ort || ag.ort || '',
      clientPhone: ag.telefon || av.telefon || '',
      clientEmail: ag.email || av.email || '',
      assignedTo:  kontaktperson,

      // Schadenort
      street,
      zip,
      city,
      address: [street, zip && city ? `${zip} ${city}` : (zip || city)].filter(Boolean).join(', '),
      locationDetails: so.etage_wohnung || so.stockwerk || so.wohnung || '',

      // Eigentümer / Rechnungsdetails (V4: alle Felder vorhanden)
      ownerName:        rd.eigentuemer || '',
      ownerStreet:      rd.strasse || '',
      ownerZip:         rd.plz || '',
      ownerCity:        rd.ort || '',
      ownerEmail:       rd.email_rechnung || '',
      invoiceReference: rd.referenz || rd.vermerk || '',

      description: beschreibung,
      status: 'Schadenaufnahme',
      date: new Date().toISOString(),

      // Priorität V4
      priority: importedData.priority || '',

      contacts: (importedData.kontakte || []).map(c => ({
        name:      c.name || c.firma || '',
        phone:     c.telefon || '',
        email:     c.email || '',
        role:      rolleMap[c.rolle] || 'Sonstiges',
        apartment: c.wohnung || c.etage || '',
        floor:     c.stockwerk || c.etage || '',
        note:      c.zweck || '',
      })),

      rooms: [],
      images: [],
      equipment: [],
      measures: '',
      findings: '',
      history: []
    };

    handleSaveReport(newReport);
    setShowEmailImport(false);
    showToast('Projekt erfolgreich importiert', 'success');
  };

  const refreshDevices = useCallback(async () => {
    try {
      if (!navigator.mediaDevices || !navigator.mediaDevices.enumerateDevices) {
        console.warn("Media devices API not available");
        return;
      }
      // Request permission only if not granted to avoid jumping UI
      await navigator.mediaDevices.getUserMedia({ audio: true }).catch(err => console.warn("Mic permission denied", err));

      const devices = await navigator.mediaDevices.enumerateDevices();
      const mics = devices.filter(d => d.kind === 'audioinput');
      setAudioDevices(mics);

      if (mics.length > 0 && !selectedDeviceId) {
        const defaultMic = mics.find(m => m.deviceId === 'default') || mics[0];
        setSelectedDeviceId(defaultMic.deviceId);
      }
    } catch (err) {
      console.error("Error enumerating devices:", err);
    }
  }, [selectedDeviceId]);

  useEffect(() => {
    refreshDevices();
  }, [refreshDevices]);

  const handleSelectDeviceId = (id) => {
    setSelectedDeviceId(id);
    localStorage.setItem('qtool_selected_mic', id);
  };

  const [toast, setToast] = useState(null);
  const showToast = (message, type = 'success') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 3000);
  };

  const ToastMarkup = toast && (
    <div style={{
      position: 'fixed',
      top: '20px',
      left: '50%',
      transform: 'translateX(-50%)',
      backgroundColor: toast.type === 'success' ? '#10B981' : '#EF4444',
      color: 'white',
      padding: '10px 20px',
      borderRadius: '8px',
      boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
      zIndex: 9999,
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      fontWeight: '500',
      animation: 'slideIn 0.3s ease-out'
    }}>
      {toast.type === 'success' ? (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"></polyline></svg>
      ) : (
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="12"></line><line x1="12" y1="16" x2="12.01" y2="16"></line></svg>
      )}
      {toast.message}
    </div>
  );

  // --- LOGIN SCREEN CHECK ---
  if (!currentUser) {
    return (
      <div className="app">
        {ToastMarkup}
        <LoginScreen users={users} onLogin={handleLogin} />
      </div>
    );
  }

  return (
    <div className="app">

      {ToastMarkup}

      <header className="app-header">
        <div className="container header-content" style={{ position: 'relative' }}>
          <div className="logo-area" style={{ flexShrink: 0 }}>
            <div className="logo-img-container">
              <img
                src="/1080p.jpg"
                alt="QService"
                style={{ height: '40px', width: 'auto' }}
                onError={(e) => { e.target.style.display = 'none'; e.target.nextSibling.style.display = 'flex'; }}
              />
              <div style={{ display: 'none', width: 40, height: 40, backgroundColor: 'var(--q-primary)', borderRadius: '50%', alignItems: 'center', justifyContent: 'center', color: 'white', fontWeight: 'bold', fontSize: '1.2rem' }}>Q</div>
            </div>
            <span style={{ fontSize: '1.1rem', fontWeight: 700, letterSpacing: '-0.02em' }}>Q-Service AG</span>
          </div>

          <nav style={{ flexGrow: 1, display: 'flex', justifyContent: 'flex-end', alignItems: 'center', gap: '0.5rem' }}>
            {view !== 'dashboard' && (
              <button className="btn btn-outline" onClick={handleCancelEntry} style={{ padding: '0.5rem 1rem' }}>
                <LayoutDashboard size={18} />
                <span className="hide-mobile">Dashboard</span>
              </button>
            )}

            {/* Mode-Toggle: immer sichtbar für admin */}
            {userRole === 'admin' && (
              <button
                className={`btn ${(view === 'dashboard' ? isTechnicianMode : projectMode === 'technician') ? 'btn-primary' : 'btn-outline'}`}
                onClick={() => {
                  if (view === 'dashboard') {
                    setIsTechnicianMode(prev => !prev)
                  } else {
                    setProjectModeExclusive(projectMode === 'technician' ? 'desktop' : 'technician')
                  }
                }}
                style={{ padding: '0.5rem 1rem' }}
                title="Zwischen Desktop- und Techniker-Modus wechseln"
              >
                {(view === 'dashboard' ? isTechnicianMode : projectMode === 'technician') ? 'Techniker' : 'Desktop'}
              </button>
            )}

            {view === 'dashboard' && (
              <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>


                {!isTechnicianMode && (
                  <>
                    <button className="btn btn-primary" onClick={() => { setSelectedReport(null); setView('new-report'); }}>
                      <Plus size={18} />
                      {i18n.t('newOrder')}
                    </button>

                    <button className="btn btn-outline" onClick={() => setShowEmailImport(true)}>
                      <Database size={18} />
                      <span className="hide-mobile">Import</span>
                    </button>

                    {/* Sync-Status Badge (Variante C: kein OneDrive-Login) */}
                    <div
                      id="sync-status-badge"
                      title={syncPending > 0
                        ? `${syncPending} Fotos ausstehend – werden synchronisiert sobald Netz verfügbar`
                        : 'Alle Daten synchronisiert'}
                      style={{
                        display: 'flex', alignItems: 'center', gap: '0.35rem',
                        padding: '0.3rem 0.65rem',
                        borderRadius: '6px',
                        border: `1px solid ${syncPending > 0 ? 'rgba(251,191,36,0.4)' : 'var(--border)'}`,
                        backgroundColor: syncPending > 0 ? 'rgba(251,191,36,0.06)' : 'var(--surface)',
                        fontSize: '0.78rem',
                        color: syncPending > 0 ? '#FBBF24' : 'var(--text-muted)',
                        whiteSpace: 'nowrap',
                        userSelect: 'none',
                        transition: 'all 0.3s ease',
                      }}
                    >
                      <span style={{
                        width: '7px', height: '7px', borderRadius: '50%',
                        backgroundColor: syncPending > 0 ? '#FBBF24' : '#10B981',
                        flexShrink: 0,
                      }} />
                      <span className="hide-mobile">
                        {syncPending > 0 ? `${syncPending} ausstehend` : 'Synchronisiert'}
                      </span>
                    </div>
                  </>
                )}

                {/* Admin Tools Group */}
                {userRole === 'admin' && !isTechnicianMode && (
                <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '3px',
                    background: isDarkMode ? 'rgba(255, 255, 255, 0.03)' : '#F4F6F9',
                    padding: '3px',
                    borderRadius: '4px',
                    border: isDarkMode ? '1px solid rgba(255,255,255,0.08)' : '1px solid #D5D9E0',
                  }}>
                    <button
                      className="btn btn-ghost"
                      onClick={handleDownloadBackup}
                      title="Backup als JSON herunterladen"
                      style={{ padding: '0.5rem', color: '#10B981' }}
                    >
                      <Download size={18} />
                    </button>
                    <button
                      className="btn btn-ghost"
                      onClick={() => {
                        if (confirm('Lokal gespeicherte Berichte (Cache) löschen? Echte Daten in der Cloud bleiben erhalten.')) {
                          localStorage.removeItem('qservice_reports_prod');
                          window.location.reload();
                        }
                      }}
                      title="Cache leeren"
                      style={{ padding: '0.5rem', color: '#FBBF24' }}
                    >
                      <RotateCcw size={18} />
                    </button>
                    <button
                      className="btn btn-ghost"
                      onClick={() => setView('devices')}
                      title="Geräteverwaltung"
                      style={{ padding: '0.5rem', color: view === 'devices' ? 'var(--q-primary)' : 'inherit' }}
                    >
                      <Settings size={18} />
                    </button>
                    <button
                      className="btn btn-ghost"
                      onClick={() => setShowMeasurementManager(true)}
                      title="Messgeräte"
                      style={{ padding: '0.5rem' }}
                    >
                      <Thermometer size={18} />
                    </button>
                    <button
                      className="btn btn-ghost"
                      onClick={() => setShowUserModal(true)}
                      title="Benutzer"
                      style={{ padding: '0.5rem' }}
                    >
                      <Users size={18} />
                    </button>
                  </div>
                )}
              </div>
            )}

            {/* Dark / Light Mode Toggle */}
            <button
              id="dark-mode-toggle"
              onClick={() => setIsDarkMode(prev => !prev)}
              title={isDarkMode ? 'Heller Modus aktivieren' : 'Dunkler Modus aktivieren'}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '0.4rem',
                background: isDarkMode ? 'rgba(255,255,255,0.06)' : '#FFFFFF',
                border: isDarkMode ? '1px solid rgba(255,255,255,0.12)' : '1px solid #D5D9E0',
                borderRadius: '4px',
                padding: '0.3rem 0.7rem',
                cursor: 'pointer',
                color: isDarkMode ? '#94A3B8' : '#4B5563',
                fontSize: '13px',
                fontWeight: 500,
                transition: 'all 0.15s ease',
                flexShrink: 0,
              }}
            >
              {isDarkMode ? <Sun size={14} /> : <Moon size={14} />}
              <span className="hide-mobile">{isDarkMode ? 'Hell' : 'Dunkel'}</span>
            </button>

            {/* User-Info – ganz rechts */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              background: isDarkMode ? 'rgba(255,255,255,0.04)' : '#F4F6F9',
              padding: '4px 10px 4px 12px',
              borderRadius: '4px',
              border: isDarkMode ? '1px solid rgba(255,255,255,0.08)' : '1px solid #D5D9E0',
              flexShrink: 0,
              marginLeft: '4px'
            }}>
              <div style={{ lineHeight: 1.25 }}>
                <div style={{ fontWeight: 600, fontSize: '13px', color: isDarkMode ? 'var(--text-main)' : '#1F2937' }}>{currentUser.name}</div>
                <div style={{ color: isDarkMode ? '#64748B' : '#6B7280', fontSize: '11px', fontWeight: 400, textTransform: 'uppercase' }}>{currentUser.role}</div>
              </div>
              <button
                onClick={handleLogout}
                className="btn btn-ghost"
                title="Abmelden"
                style={{ padding: '4px', color: isDarkMode ? '#F87171' : '#6B7280', borderRadius: '3px' }}
              >
                <LogOut size={14} />
              </button>
            </div>
          </nav>
        </div>
      </header>

      <main className="container" style={{ marginTop: effectiveMode === 'technician' ? '0.5rem' : '1rem', padding: effectiveMode === 'technician' ? '0.5rem' : '1rem 1.25rem', maxWidth: effectiveMode === 'technician' ? undefined : 'none' }}>

        {/* ── Supabase Debug-Banner: zeigt Verbindungsstatus für iPad-Diagnose ── */}
        {view === 'dashboard' && supabaseStatus && (
          <div style={{
            marginBottom: '1rem',
            padding: '0.6rem 1rem',
            borderRadius: '8px',
            fontSize: '0.8rem',
            fontWeight: 600,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '1rem',
            backgroundColor: supabaseStatus.ok === null
              ? 'rgba(99,102,241,0.1)'
              : supabaseStatus.ok
                ? 'rgba(16,185,129,0.1)'
                : 'rgba(239,68,68,0.1)',
            border: `1px solid ${supabaseStatus.ok === null ? '#6366f1' : supabaseStatus.ok ? '#10B981' : '#EF4444'}44`,
            color: supabaseStatus.ok === null ? '#6366f1' : supabaseStatus.ok ? '#10B981' : '#EF4444',
          }}>
            <span>
              {supabaseStatus.ok === null && '⏳ Verbinde mit Supabase...'}
              {supabaseStatus.ok === true && `✅ ${supabaseStatus.count} Projekte geladen (${supabaseStatus.total} DB-Einträge)`}
              {supabaseStatus.ok === false && `❌ Supabase Fehler: ${supabaseStatus.error}`}
            </span>
            <button
              onClick={() => setSupabaseStatus(null)}
              style={{ background: 'none', border: 'none', cursor: 'pointer', opacity: 0.6, fontSize: '1rem', color: 'inherit' }}
            >✕</button>
          </div>
        )}

        {view === 'dashboard' && <Dashboard
          reports={reports}
          onSelectReport={handleSelectReport}
          onDeleteReport={handleDeleteReport}
          mode={isTechnicianMode ? 'technician' : 'desktop'}
          supabase={supabase}
          currentUser={currentUser}
          users={users}
          lockedProjectIds={lockedProjectIds}
          onLogout={handleLogout}
          onReportsChanged={async () => {
            // Reload from Supabase after a status change
            const { data } = await supabase.from('damage_reports').select('report_data, updated_at').order('created_at', { ascending: false });
            if (data) setReports(data.map(r => ({ ...r.report_data, _supabase_updated_at: r.updated_at })).filter(r => !r._isSession && !r.deleted_at));
          }}
        />}
        {view === 'devices' && <DeviceManager reports={reports} onBack={() => setView('dashboard')} onNavigateToReport={handleNavigateToReport} />}
        {(view === 'new-report' || view === 'details') && (
          <div style={{ position: 'relative' }}>
            {/* ── Sitzungssperre: Overlay + UI gesperrt wenn anderer Modus aktiv ── */}
            {isLockedByOtherMode && (
              <div style={{
                position: 'absolute',
                top: 0, left: 0, right: 0, bottom: 0,
                zIndex: 9000,
                backgroundColor: 'rgba(220, 38, 38, 0.08)',
                cursor: 'not-allowed',
                pointerEvents: 'all',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                minHeight: '60vh',
              }}>
                <div style={{
                  background: 'rgba(220,38,38,0.92)',
                  color: 'white',
                  padding: '1.5rem 2.5rem',
                  borderRadius: '16px',
                  fontWeight: 800,
                  fontSize: '1.1rem',
                  textAlign: 'center',
                  boxShadow: '0 8px 40px rgba(220,38,38,0.5)',
                  maxWidth: '400px',
                  lineHeight: 1.8,
                  pointerEvents: 'all',
                  cursor: 'default',
                  display: 'flex',
                  flexDirection: 'column',
                  gap: '1rem',
                }}>
                  <div>
                    🔒 Projekt gesperrt<br />
                    <span style={{ fontWeight: 400, fontSize: '0.9rem' }}>
                      {sessionLockMessage}
                    </span>
                  </div>
                  <button
                    onClick={async () => {
                      // Session-Lock erzwingen
                      await takeOverLock();
                    }}
                    style={{
                      background: 'white', color: '#dc2626',
                      border: 'none', padding: '0.6rem 1.2rem',
                      borderRadius: '8px', fontWeight: 800,
                      fontSize: '0.95rem', cursor: 'pointer',
                    }}
                  >
                    → Hier weiterarbeiten
                  </button>
                </div>
              </div>
            )}
            <DamageForm
              key={selectedReport ? selectedReport.id : 'new'}
              onCancel={handleCancelEntry}
              onSave={handleSaveReport}
              initialData={selectedReport}
              mode={projectMode}
              readOnly={isReadOnly}
              isDarkMode={isDarkMode}
              onModeChange={(newMode) => {
                setProjectModeExclusive(newMode);
              }}
            />
          </div>
        )}
      </main>

      {/* Render User Management Modal */}
      {showUserModal && <UserManagementModal onClose={() => setShowUserModal(false)} users={users} setUsers={setUsers} />}
      {showMeasurementManager && <MeasurementDeviceManager onClose={() => setShowMeasurementManager(false)} />}
      {showEmailImport && (
        <EmailImportModalV2
          onClose={() => setShowEmailImport(false)}
          onImport={handleEmailImport}
          audioDevices={audioDevices}
          selectedDeviceId={selectedDeviceId}
          onSelectDeviceId={handleSelectDeviceId}
          onRefreshDevices={refreshDevices}
        />
      )}
    </div>
  )
}

export default App
