/* ==========================================================================
   AI-ASSISTANT LOCK: DO NOT EDIT THIS FILE OR ITS LOGIC WITHOUT EXPLICIT 
   PERMISSION FROM THE USER. THIS APPLIES TO CORE/CRITICAL LOGIC.
   ========================================================================== */
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './tw.css'
import './index.css'
import ErrorBoundary from './ErrorBoundary.jsx'
import { isOneDrivePopupCallback } from './lib/onedrive/popupCallback.js'
import { completeOneDrivePopup } from './lib/onedrive/popupBridge.js'

// A previously installed production PWA must never cache local development
// bundles. Otherwise the browser can keep serving an old login implementation
// even while Vite has already rebuilt the current source.
if (import.meta.env.DEV) {
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.getRegistrations()
      .then(registrations => Promise.all(registrations.map(registration => registration.unregister())))
      .catch(error => console.warn('[Dev] Service-Worker konnte nicht entfernt werden:', error));
  }
  if ('caches' in window) {
    caches.keys()
      .then(keys => Promise.all(keys.map(key => caches.delete(key))))
      .catch(error => console.warn('[Dev] PWA-Cache konnte nicht geleert werden:', error));
  }
}

const rootElement = document.getElementById('root');
const isPopupCallback = isOneDrivePopupCallback(
  window.location,
  window.opener !== null
);

if (isPopupCallback) {
  const root = createRoot(rootElement);
  root.render(
    <main
      role="status"
      aria-live="polite"
      style={{
        minHeight: '100vh',
        display: 'grid',
        placeItems: 'center',
        padding: '2rem',
        background: '#0f1b2e',
        color: '#f8fafc',
        fontFamily: 'system-ui, sans-serif',
      }}
    >
      <div style={{ display: 'grid', gap: '.75rem', textAlign: 'center' }}>
        <strong>OneDrive-Anmeldung wird abgeschlossen…</strong>
        <span>Dieses Fenster schließt automatisch.</span>
      </div>
    </main>
  );

  completeOneDrivePopup().catch((error) => {
    console.error('[OneDrive] OAuth-Callback konnte nicht abgeschlossen werden:', error);
    root.render(
      <main
        role="alert"
        style={{
          minHeight: '100vh',
          display: 'grid',
          placeItems: 'center',
          padding: '2rem',
          background: '#0f1b2e',
          color: '#f8fafc',
          fontFamily: 'system-ui, sans-serif',
        }}
      >
        <div style={{ display: 'grid', gap: '.75rem', maxWidth: '32rem', textAlign: 'center' }}>
          <strong>OneDrive-Anmeldung konnte nicht abgeschlossen werden.</strong>
          <span>Schließe dieses Fenster und starte die Verbindung im Hauptfenster erneut.</span>
        </div>
      </main>
    );
  });
} else {
  // ─── Variante C: Offline-Blobs → Supabase Storage synchen (kein MSAL) ─────
  // Startet beim App-Boot im Hintergrund, blockiert Render nicht.
  import('./lib/sync/supabaseSyncWorker.js')
    .then(({ syncPendingToSupabase }) => syncPendingToSupabase())
    .then(({ synced }) => { if (synced > 0) console.info(`[Boot] ☁️ ${synced} Fotos zu Supabase synchronisiert`); })
    .catch((e) => console.warn('[Boot] Sync fehlgeschlagen:', e.message));

  // ─── App rendern (kein MSAL-Provider nötig) ────────────────────────────────
  import('./App.jsx').then(({ default: App }) => {
    const root = createRoot(rootElement);
    root.render(
      <ErrorBoundary>
        <App />
      </ErrorBoundary>
    );
  }).catch(err => {
    console.error('[QTool] Ladefehler:', err);
  });
}
